chat_home:
  path: /
  defaults: { _controller: ChatBundle:Chat:index }
  methods: [GET, POST]

chat_send_message:
  path: /send
  defaults: { _controller: ChatBundle:Chat:sendMessage }
  methods: POST
