
services:
  generate_uuid_service:
    class: ChatBundle\Libraries\Util\GenerateUUIDService

  user_service:
    class: ChatBundle\Libraries\Helper\User\UserService
    arguments: ['@doctrine.orm.entity_manager']

  message_service:
    class: ChatBundle\Libraries\Helper\Message\MessageService
    arguments: ['@doctrine.orm.entity_manager']
